name: "Airport Checkin"

on:
  schedule:
    - cron: "15 16 * * *"  # scheduled at 00:15 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-100 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run sign
        env:
          URL: ${{ secrets.URL }}
          INFO: ${{ secrets.INFO }}
          SMTP: ${{ secrets.SMTP}}
        run: |
          python3 ./main2.py
